keycloak:
  # keycloak的地址
  auth-server-url: https://bocsys.xyz:8443/auth/
  # keycloak中的realm
  realm: master
  resource: hellokeycloak
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
  principal-attribute: preferred_username
server:
  port: 8081
  ssl:
    key-store: server.jks
    key-store-password: BOChq999
    keyStoreType: JKS
    keyAlias: alias
spring: 
  security: 
    user:
      name: admin
      password: admin